interface IWordLists {
  [key: string]: {
    [key: string]: string[];
  };
}

const wordLists: IWordLists = {
  fruit: {
    easy: [
      "apple",
      "banana",
      "orange",
      "mango",
      "grape",
      "strawberry",
      "kiwi",
      "blueberry",
      "pineapple",
      "lemon",
      "cherry",
      "raspberry",
      "pear",
      "plum",
      "melon",
      "peach",
      "apricot",
      "pomegranate",
      "coconut",
      "fig",
    ],
    medium: [
      "watermelon",
      "guava",
      "blackberry",
      "kiwifruit",
      "papaya",
      "dragon fruit",
      "nectarine",
      "passion fruit",
      "lime",
      "cantaloupe",
      "grapefruit",
      "lychee",
      "persimmon",
      "mulberry",
      "pomegranate",
      "coconut",
      "fig",
      "mangosteen",
      "tamarind",
      "guanabana",
    ],
    hard: [
      "apricot",
      "avocado",
      "rambutan",
      "soursop",
      "jackfruit",
      "starfruit",
      "carambola",
      "gooseberry",
      "quince",
      "feijoa",
      "marula",
      "ackee",
      "cupuacu",
      "custard apple",
      "jabuticaba",
      "pitahaya",
      "sapodilla",
      "longan",
      "kiwano",
      "buddha's hand",
    ],
    extreme: [
      "jackfruit",
      "persimon",
      "dragonfruit",
      "passion fruit",
      "quince",
      "ackee",
      "feijoa",
      "pitahaya",
      "cupuacu",
      "sapodilla",
      "mangosteen",
      "longan",
      "kiwano",
      "buddha's hand",
      "soursop",
      "cherimoya",
      "custard apple",
      "jabuticaba",
      "tamarillo",
      "miracle fruit",
    ],
  },
  country: {
    easy: [
      "indonesia",
      "malaysia",
      "thailand",
      "vietnam",
      "laos",
      "philippines",
      "singapore",
      "cambodia",
      "myanmar",
      "brunei",
      "timor-leste",
      "mongolia",
      "afghanistan",
      "bhutan",
      "bangladesh",
      "pakistan",
      "nepal",
      "sri lanka",
      "maldives",
      "india",
    ],
    medium: [
      "russia",
      "japan",
      "china",
      "korea",
      "india",
      "turkey",
      "germany",
      "france",
      "italy",
      "spain",
      "united kingdom",
      "australia",
      "canada",
      "brazil",
      "argentina",
      "mexico",
      "egypt",
      "south africa",
      "nigeria",
      "ethiopia",
    ],
    hard: [
      "cuba",
      "greenland",
      "nepal",
      "nigeria",
      "egypt",
      "poland",
      "sweden",
      "norway",
      "finland",
      "ireland",
      "jamaica",
      "colombia",
      "chile",
      "peru",
      "venezuela",
      "uganda",
      "tanzania",
      "rwanda",
      "zambia",
      "zimbabwe",
    ],
    extreme: [
      "comoros",
      "dominica",
      "liechtenstein",
      "nauru",
      "tuvalu",
      "sao tome and principe",
      "palau",
      "grenada",
      "kiribati",
      "lesotho",
      "marshall islands",
      "saint kitts and nevis",
      "seychelles",
      "vanuatu",
      "tonga",
      "san marino",
      "micronesia",
      "andorra",
      "barbados",
      "suriname",
    ],
  },
  animal: {
    easy: [
      "cat",
      "dog",
      "duck",
      "chicken",
      "cow",
      "sheep",
      "pig",
      "horse",
      "rabbit",
      "goat",
      "elephant",
      "monkey",
      "deer",
      "mouse",
      "bird",
      "snake",
      "fish",
      "turtle",
      "fox",
      "bear",
    ],
    medium: [
      "ant",
      "wolf",
      "bear",
      "lion",
      "tiger",
      "cheetah",
      "elephant",
      "giraffe",
      "rhinoceros",
      "hippopotamus",
      "zebra",
      "panther",
      "leopard",
      "kangaroo",
      "coyote",
      "hyena",
      "jaguar",
      "lynx",
      "bobcat",
      "cougar",
    ],
    hard: [
      "penguin",
      "kangaroo",
      "giraffe",
      "gazelle",
      "crocodile",
      "hippopotamus",
      "rhinoceros",
      "buffalo",
      "hippopotamus",
      "gorilla",
      "chimpanzee",
      "elephant",
      "ostrich",
      "tapir",
      "platypus",
      "gibbon",
      "okapi",
      "anteater",
      "wolverine",
      "porcupine",
    ],
    extreme: [
      "xenotarsosaurus",
      "dendrocnide",
      "placentalia",
      "cyphochilus",
      "xiphosura",
      "brachycorythis",
      "scolopendra",
      "haplochromis",
      "xenopholis",
      "erythrolamprus",
      "xenopeltis",
      "megachile",
      "gnathonemus",
      "ophryocystis",
      "heliobolus",
      "chromodoris",
      "xiphophorus",
      "paralepididae",
      "colostethus",
      "platybelodon",
    ],
  },
};

export default wordLists